### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by SeanTolstoyevski** [Zuzu-Typ/PyOpenAL#12]
Hi,

this repo I couldn't find any documents about PyALL in this repo.

Where can I find documents describing PyALL in detail?

**Comment by Zuzu-Typ** [comment]
Hello Sean,

I'm not sure this is what you're looking for at all.

First of all, "PyALL" doesn't exist. There is no such library (at least in the [PyPI](https://pypi.org/search/?q=PyALL).

This (PyOpenAL) is a library that provides bindings to [OpenAL](https://www.openal.org/).
You'll find advanced documentation on their site.

Aside from that, PyOpenAL provides a few of it's own methods. They're documented in the [README](https://github.com/Zuzu-Typ/PyOpenAL#reference-for-pyopenals-own-classes-and-functions).
