### ISSUE TITLE
DLL load Error

### ISSUE THREAD

**Issue by SeanTolstoyevski** [Zuzu-Typ/PyOpenAL#13]
Hi ,
How can I load pyopenal32.dll or soft_oal.dll.
I'm getting an error.

I create a folder named lib inside the pyopenal folder.
or lib \ 32bit
or lib \ 64bit
I copy openal32.dll to these folders, I get an error.

I am copying the dll to a path I added to sys.path. not happening again.

thanks.

```
  File "userConfig\addons\speedExplorer\globalPlugins\SpeedExplorer\openal\__init__.py", line 1, in <module>
    from .al import *
  File "userConfig\addons\speedExplorer\globalPlugins\SpeedExplorer\openal\al.py", line 6, in <module>
    from .al_lib import lib
  File "userConfig\addons\speedExplorer\globalPlugins\SpeedExplorer\openal\al_lib.py", line 12, in <module>
    raise ExternalLibraryError("OpenAL library couldn't be found")
openal.library_loader.ExternalLibraryError: OpenAL library couldn't be found
```

**Comment by Zuzu-Typ** [comment]
Well, PyOpenAL doesn't search in any subfolders, unless they are specified in the environment variables.
You should be able to add your subdirectories to the internal python environment variables using
`os.environ["PATH"] += ";" + os.path.realpath("lib/32bit") + ";" + os.path.realpath("lib/64bit")`
or something similar.
You would have to put that _before_ the `import openal` statement though.

**Comment by SeanTolstoyevski** [comment]
Hi @Zuzu-Typ ,

Thank you for your help.
Everything is working now.

Can you add a note about it to Readme?
I think others are having the same problem.
and 3d player example. I really need this.
It is difficult to read and understand the C document for someone who knows only python.

**Comment by Zuzu-Typ** [comment]
I'm currently focussing my work on other libraries and unfortunately I don't have a lot of time to begin with. 
Nonetheless, I will try to improve PyOpenAL in the future.
