### ISSUE TITLE
How can I play only part of the audio？

### ISSUE THREAD

**Issue by 1994cxy** [Zuzu-Typ/PyOpenAL#19]
In my code, I want to play part of the audio depending on some conditions.
The oalOpen() function returns an object and I don't know how to do the slice operation on it.
@Zuzu-Typ

**Comment by Zuzu-Typ** [comment]
Hi @1994cxy ,

unfortunately this isn't trivially possible, because openAL does not have a dedicated function for this purpose.

It would be required to do something like this: http://lebagage.free.fr/en/indexe9c7.html?Welcome:OpenAL_-_start_track_not_at_origin_(seek_pos)

This is C code though and not Python code.

Sadly I don't have enough time to work on this project myself :(

**Comment by 1994cxy** [comment]
> Hi @1994cxy ,
> 
> unfortunately this isn't trivially possible, because openAL does not have a dedicated function for this purpose.
> 
> It would be required to do something like this: http://lebagage.free.fr/en/indexe9c7.html?Welcome:OpenAL_-_start_track_not_at_origin_(seek_pos)
> 
> This is C code though and not Python code.
> 
> Sadly I don't have enough time to work on this project myself :(

Thanks for your answer~

I write a new WaveFile class to slice the buffer according to the sampwidth from the wave lib. I don't know if I am right, but this part of the code works fine right now.

However, I encountered another error in my code. 

In fact, I want to implement an API that can put an audio source in front of the listener and rotate another source around the same listener. 

I implemented my code base on PyOpenAL-HRTF which is a fork of this project. Here is my code:

```python
def stereo_play(attended_path, unattended_path, hrtf_type=None):
    if hrtf_type:
        hrtf_name = hrtf_type
    else:
        hrtf_name = None

    # Initialize PyOpenAL
    oalInit()

    # Initialize HRTFs
    oalInitHRTF(requested_hrtf=hrtf_name)

    # Create a listener at (0,0,0)
    listener = Listener()
    listener.set_position((0, 0, 0))

    # Create sources to play sound with
    # source_att = oalOpen(attended_path)
    # source_unatt = oalOpen(unattended_path)

    source_att, nframes = create_source(attended_path, None)
    source_unatt, _ = create_source(unattended_path, nframes)

    # Set position of source always relative to the listener
    source_att.relative = True
    source_unatt.relative = True

    # Set position of source
    source_att.set_position((0., 1., 0))
    source_unatt.set_position((0., 0., -1.))

    # Start playing source until it finishes
    source_att.play()
    source_unatt.play()

    angle = 0
    while source_att.get_state() == al.AL_PLAYING or source_unatt.get_state() == al.AL_PLAYING:
        time.sleep(0.05)

        # Rotate the source around the lsitener
        # (Taken almost verbatim from alhrtf.c)
        angle += 0.01 * np.pi * 0.5
        if angle > np.pi:
            angle -= np.pi * 2.0

        # Update source position
        source_unatt.set_position((np.sin(angle), 0., -np.cos(angle)))

        # Try to alter stereo angles
        source_unatt.set_stereo_angles((np.pi / 6.0 - angle, -np.pi / 6.0 - angle))

    # Clear up everything
    oalQuit()
```

When I use the function above in a for-loop, I get the error:

```python
Traceback (most recent call last):
  File "XXX\.conda\envs\py39\lib\site-packages\pyopenal_hrtf-0.7.11a1-py3.9.egg\openal\__init__.py", line 877, in oalQuit
    buffer.destroy()
  File "XXX\.conda\envs\py39\lib\site-packages\pyopenal_hrtf-0.7.11a1-py3.9.egg\openal\__init__.py", line 417, in destroy
    alDeleteBuffers(1, ctypes.pointer(self.id))
  File "XXX\.conda\envs\py39\lib\site-packages\pyopenal_hrtf-0.7.11a1-py3.9.egg\openal\al.py", line 96, in al_check_error
    raise ALError(al_enums[err][0])
openal.al.ALError: AL_INVALID_OPERATION
```

**Comment by 1994cxy** [comment]
Here is my definition of the create_source function which uses the new WaveFile class (MyWaveFile) to slice the wav file
```python
def create_source(path, length=None):
    file_ = MyWaveFile(path, length)
    buffer_ = Buffer(file_)
    source = Source(buffer_, True)

    return source, file_.nframes
```

**Comment by Zuzu-Typ** [comment]
Hmm.. From just looking at your code, everything seems to be in order. At least I didn't spot any potential problems. Then again it's been years since I've last worked on this library 😅

Does the same issue occur when using the built-in WaveFile class?

I believe this error only occurs if a buffer is destroyed more than once, or a buffer is queued for deletion that doesn't actually exist.
Because I didn't know better at the time, I didn't install any safeguards to prevent this from happening.

**Comment by 1994cxy** [comment]
I already solve this problem and your advice is very helpful~ Thanks~
