### ISSUE TITLE
Playing short wave streams results in errors

### ISSUE THREAD

**Issue by rspencer01** [Zuzu-Typ/PyOpenAL#4]
The code

    import openal
    from time import *
    s = openal.oalStream('short.wav')
    s.play()
    for _ in xrange(100):
        s.update()
        sleep(0.1)

results in error

      File "/home/robert/src/PyOpenAL/openal/__init__.py", line 841, in oalStream
        return SourceStream(stream)
      File "/home/robert/src/PyOpenAL/openal/__init__.py", line 698, in __init__
        alSourceQueueBuffers(self.id, OAL_STREAM_BUFFER_COUNT, self.buffer.buffer_ids)
      File "/home/robert/src/PyOpenAL/openal/_al.py", line 120, in al_check_error
        raise ALError(al_enums[err][0])
    openal._al.ALError: AL_INVALID_OPERATION

But replacing `'short.wav'` with `long.wav` does not.  (obviously `short.wav` is a short (under 1s) sound file, and `long.wav` is longer).

**Comment by Zuzu-Typ** [comment]
Thanks for reporting!
Should be fixed now.
