### ISSUE TITLE
Don't destroy the buffer when a source is destroyed

### ISSUE THREAD

**Issue by pmiddend** [Zuzu-Typ/PyOpenAL#6]
Sources seem to be a limited resources. In my application, I get an out of memory as soon as the number of sources reaches a critical amount.
Consequently, I destroyed my sources as soon as they were done playing (e.g. `AL_STOPPED`). This lead to an exception when calling `oalQuit`, for two reasons:

1. `Source` appends to the `_items` list, but doesn't remove itself on destruction
2. Destroying a source also destroys the underlying buffer. That's not the intention of sources, however. Buffers can be kept and re-used. And there might be more than one source for every buffer (at different positions, for example).

This should both be fixed.

**Comment by Zuzu-Typ** [comment]
I'm sorry for the delay.

The issue should be fixed now.

Destroying the buffer is now optional (for Source objects, not for SourceStream objects) and can be activated by setting the keyword argument "destroy_buffer" to True.
