### ISSUE TITLE
PyOpenAL is broken on pyinstaller (or in general)

### ISSUE THREAD

**Issue by pmiddend** [Zuzu-Typ/PyOpenAL#7]
In `library_loader.py`, you have an `if` statement that checks if the library to be loaded is a file (line 73). This check is dangerous, because the `CDLL` constructor is actually able to load files for which the `if` fails. This happened to me when I tried to package my program with the popular tool pyinstaller.

To fix this, I think we can just remove the `if`, or did you have special requirements for the inclusion?

**Comment by Zuzu-Typ** [comment]
Could you please explain why you think the if statement should be removed?
The library has to be a file - to avoid having folders mistaken for libraries, they are checked to be files.

PyOpenAL can be built using PyInstaller - do you have any specific issues with the building process?

**Comment by pmiddend** [comment]
Two things:

1. in pyogg, you don't have this line, and pyogg works out of the box.
2. `CDLL` can, of course, only load files, but those files don't have to have an absolute path. You can specify `foo.dll` and `CDLL` will search for this file in system search paths.

**Comment by Zuzu-Typ** [comment]
library_loader now uses find_library to locate libraries on Windows as well - technically this should fix your problem or create new ones..
Please let me know if that helps
