### ISSUE TITLE
Playing a vorbis file crashes python

### ISSUE THREAD

**Issue by kiwec** [Zuzu-Typ/PyOpenAL#9]
This looks related to https://github.com/Zuzu-Typ/PyOgg/issues/10 but might not be.
It's not crashing when loading, but when playing - using the default windows openal32.dll.
It works just fine playing opus or wave files.

Here is the code and file used :

```python
import time
from openal import *

source = oalOpen('test.ogg')
source.play()

while source.get_state() == AL_PLAYING:
	time.sleep(1)

oalQuit()
```

https://files.catbox.moe/wr9w16.ogg (github doesn't allow ogg uploads)

**Comment by Zuzu-Typ** [comment]
Thank you for letting me know.

Indeed, it was an issue on PyOgg's side.

It should be fixed now.
